name: Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v2
      - name: Run tests
        uses: php-actions/composer@v2
        with:
          command: test
          suggest: 'yes'
          progress: 'yes'
